### ISSUE TITLE
ajout script ortholog

### ISSUE THREAD

**Issue by OlivierClerc** [ntm/IDN#51]
Sur la machine de Madeline, dans /home/matrixdb/matrixdb_InConstruction/data_Backbone/biomoleculeData/scriptMade/Orthologs/
- j'ai cree un repertoire Old/ dans lequel j'ai mis les anciens fichiers
- j'ai copie le script permettant de trouver les orthologues humains des biomolecules non humaines, les 2 fichiers d'entree ainsi que le fichier de sortie
- j'ai modifie le README

**Comment by ntm** [comment]
AOK, synchro sur serveur done.
