### ISSUE TITLE
Modif mineure script Ortholog et push sur serveur

### ISSUE THREAD

**Issue by OlivierClerc** [ntm/IDN#52]
J'ai fait une modification mineure du script findOrtho.py situe dans /home/matrixdb/matrixdb_InConstruction/data_Backbone/biomoleculeData/scriptMade/Orthologs/
Il s'agit d'incrementations et de commentaires.
J'ai l'ai teste et ai compare les fichiers resultats avec ceux precedants : aucune difference.

J'ai fait un push du dossier Orthologs/ de la machine de Madeline vers le serveur MatrixDB.

**Comment by ntm** [comment]
AOK
